version: 1.36.2.{build}
os: Visual Studio 2017
clone_folder: C:\Projects\MaterialX

environment:
  matrix:
#   - CMAKE_PLATFORM: "Visual Studio 15 2017"
#     PYTHON: C:\Python36
#     VS_PLATFORM: Windows_x86
#     VS_COMPILER: vs2017
#     configuration: Release
    - CMAKE_PLATFORM: "Visual Studio 15 2017 Win64"
      PYTHON: C:\Python37-x64
      VS_PLATFORM: Windows
      VS_COMPILER: vs2017
      configuration: Release

install:
  - git submodule update --init --recursive
  - set PATH=%PYTHON%;%PATH%

build_script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake -DMATERIALX_BUILD_PYTHON=ON -DMATERIALX_BUILD_VIEWER=ON -DMATERIALX_WARNINGS_AS_ERRORS=ON -G "%CMAKE_PLATFORM%" -DCMAKE_BUILD_TYPE="%CONFIGURATION%" ..
  - cmake --build . --target install --config %CONFIGURATION%
  - ctest --output-on-failure --build-config %CONFIGURATION%
  - cmake -E chdir ../python/MaterialXTest python main.py
  - cd C:\Projects\MaterialX\build\installed
  - 7z a -r C:\Projects\MaterialX\materialx-v1.36.0_shaderx-%VS_PLATFORM%-%CONFIGURATION%.zip .
  - cd C:\Projects\MaterialX\build\source\MaterialXView\Release\
  - 7z a -r C:\Projects\MaterialX\materialx-v1.36.0_viewer-%VS_PLATFORM%-%CONFIGURATION%.zip .
  - dir /s /b C:\Projects\MaterialX\

artifacts:
    # Set artifact to be created zip.  Currently marked as pre-release
    - path: materialx-v1.36.0_shaderx-%VS_PLATFORM%-%CONFIGURATION%.zip
      name: MaterialX_ADSK
    - path: materialx-v1.36.0_viewer-%VS_PLATFORM%-%CONFIGURATION%.zip
      name: MaterialX_Viewer
